name: fixify
description: A Flutter mobile app for citizens to report issues and earn green coins.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  flutter_riverpod: ^2.5.1
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.0.0
  camera: ^0.10.5+9
  mobile_scanner: ^3.5.5
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^17.2.2
  google_maps_flutter: ^2.5.3
  fl_chart: ^0.66.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
